apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.yaml: |
    verbose: true
    auth_token: test_token
    key_version: 1
    otlp_endpoint: http://jaeger-svc:4317
    redis:
      url: redis://redict-svc:6379/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redict-config
data:
  redict.conf: |
    dir /var/data
    appendonly yes
    loglevel verbose
