apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravenx-url
spec:
  selector:
    matchLabels:
      app: ravenx-url
  template:
    metadata:
      labels:
        app: ravenx-url
    spec:
      containers:
        - name: redict
          image: registry.redict.io/redict:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/data"
              name: redict-pvc
        - name: ravenx-url-nginx
          image: ghcr.io/alfreddobradi/ravenx-url:v1.0.1
          command:
            - 'ravenx'
            - '--config-path'
            - '/etc/ravenx/config.yaml'
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: "/etc/ravenx"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: app-config
        - name: redict-pvc
          persistentVolumeClaim:
            claimName: ravenx-url-redis-claim
