apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravenx-url
spec:
  selector:
    matchLabels:
      app: ravenx-url
  template:
    metadata:
      labels:
        app: ravenx-url
    spec:
      containers:
        - name: ravenx-url-nginx
          image: ghcr.io/alfreddobradi/ravenx:v1.2.1
          command:
            -
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
          volumeMounts:
            - name: foo
              mountPath: "/etc/ravenx"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: app-config
