apiVersion: v1
kind: Service
metadata:
  name: ravenx-url-web
spec:
  selector:
    app: ravenx-url
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: redict-svc
spec:
  selector:
    app: ravenx-url
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
spec:
  selector:
    app: ravenx-url
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: ingest
      port: 4317
      targetPort: 4317
